source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.3'

# ignore all warnings from all pods
inhibit_all_warnings!

# use frameworks for Swift
use_frameworks!

project 'RPCircularProgressExample'

target 'RPCircularProgressExample' do
  # Autolayout
  pod 'SnapKit', '~> 4.0.0'

  target 'RPCircularProgressTests' do
    inherit! :search_paths

    # Tests
    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
