platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

# use frameworks for Swift
use_frameworks!

target "RPCircularProgressExample" do
    # Autolayout
    pod 'SnapKit'
end

target "RPCircularProgressTests" do
    # Tests
    pod 'Quick'
    pod 'Nimble'
end
